In [5]:
import numpy as np
import pandas as pd
df=pd.read_csv("iris_dataset.csv")
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 5 columns]

In [4]:
df.iloc[:,1:4]

sepal width (cm)  petal length (cm)  petal width (cm)
0                 3.5                1.4               0.2
1                 3.0                1.4               0.2
2                 3.2                1.3               0.2
3                 3.1                1.5               0.2
4                 3.6                1.4               0.2
..                ...                ...               ...
145               3.0                5.2               2.3
146               2.5                5.0               1.9
147               3.0                5.2               2.0
148               3.4                5.4               2.3
149               3.0                5.1               1.8

[150 rows x 3 columns]

In [6]:
x=df.iloc[:,1:4].values

In [7]:
y=df.iloc[:,4].values

In [7]:
y  #it display taget --- string

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [8]:
#To convert string to integer ---used LabelEncoder
from sklearn.preprocessing import LabelEncoder
labelencoder_y= LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [11]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)


LogisticRegression()

In [13]:
y_pred=logmodel.predict(x_test)

In [14]:
y_pred

array([0, 1, 0, 0, 1, 2, 1, 0, 2, 2, 2, 1, 0, 2, 1, 1, 1, 1, 0, 0, 2, 1,
       2, 1, 2, 0, 2, 0, 1, 1])

In [15]:
y_test

array([0, 1, 0, 0, 1, 2, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 0, 0, 2, 1,
       2, 1, 2, 0, 2, 0, 1, 1])

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  1,  8]])

28


In [19]:
28/30  # (9+11+8)/sum of all elements

0.9333333333333333

In [20]:
from sklearn.neighbors import KNeighborsClassifier   #classification alogorithm---wo distances pe kam karta hai...kom=nsa point kis point se near hai
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2) #5 nearest neigbors ko check karega,decide mejority
classifier_knn.fit(x_train,y_train)


KNeighborsClassifier()

In [21]:
y_pred=classifier_knn.predict(x_test)

In [22]:
confusion_matrix(y_test,y_pred)


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  2,  7]])

In [23]:
9+11+7/9+11+7+1+2

41.77777777777778

In [24]:
from sklearn.naive_bayes import GaussianNB
classifier_nb=GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [25]:
y_pred=classifier_nb.predict(x_test)

In [26]:
confusion_matrix(y_test,y_pred)


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  2,  7]])

In [27]:
27/30

0.9

In [28]:
from sklearn.svm import SVC  #support vector machine algorithm
classifier_svm_sigmoid=SVC(kernel='sigmoid')   #kernal-sigmoid,linear,rbf,polynomial
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [29]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [30]:
confusion_matrix(y_test,y_pred)


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  2,  7]])

In [31]:
27/30

0.9

In [32]:
from sklearn.svm import SVC
classifier_svm_linear=SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [33]:
y_pred=classifier_svm_linear.predict(x_test)

In [34]:
confusion_matrix(y_test,y_pred)


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  1,  8]])

In [35]:
9+11+8/9+11+8+1+1

41.888888888888886

In [36]:
from sklearn.svm import SVC
classifier_svm_rbf=SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [37]:
y_pred=classifier_svm_rbf.predict(x_test)

In [38]:
confusion_matrix(y_test,y_pred) #to calculate accuracy


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  0,  9]])

In [39]:
9+11+9/9+11+9+1

42.0

In [40]:
from sklearn.svm import SVC
classifier_svm_poly=SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [41]:
y_pred=classifier_svm_poly.predict(x_test)

In [42]:
confusion_matrix(y_test,y_pred) #to calculate accuracy


array([[ 9,  0,  0],
       [ 0, 11,  1],
       [ 0,  1,  8]])

In [43]:
9+11+8/9+11+8+1+1

41.888888888888886

In [ ]:
#sklearn using Movies dataset project in ml
#Confusion Matrix helps evaluate classification performance, providing detailed metrics such as precision, recall, F1-score, and accuracy,
#making it essential for understanding model behavior, especially on imbalanced datasets.